version: "3.9"

services:

  db_users:
    image: postgres:latest
    container_name: FastApiPostgresUsers
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.0"
    container_name: FastApiRedisUsers
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"